# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
#

name: Node.js CI
on:
  push:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install Dependencies
        run: |
          npm install \
            "@expo/webpack-config@^19.0.0" \
            "@react-navigation/native-stack@^6.9.13" \
            "axios@^1.5.0" \
            "expo@49.0.9" \
            "expo-cli@^6.3.10" \
            "expo-constants@~14.4.2" \
            "expo-linking@~5.0.2" \
            "expo-router@^2.0.5" \
            "expo-status-bar@~1.6.0" \
            "jwt-decode@^3.1.2" \
            "metro@0.76.7" \
            "metro-inspector-proxy@^0.78.1" \
            "react@18.2.0" \
            "react-dom@18.2.0" \
            "react-native@0.72.4" \
            "react-native-gesture-handler@~2.12.0" \
            "react-native-safe-area-context@4.6.3" \
            "react-native-screens@~3.22.0" \
            "react-native-web@~0.19.6" \
            "react-navigation@^4.4.4" \
            "react-navigation-stack@^2.10.4" \
            "serve@^14.2.1"

    - run: npm run prod
