name: Copy Files to EC2 Windows

on:
  push:
    branches:
      - dev  # Configure a branch que desencadeará o fluxo de trabalho

jobs:
  copy-to-ec2:
    runs-on: windows-latest  # Use uma máquina Windows

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Verifique o código do repositório

    - name: Copy Files to EC2
      env:
        LOCAL_PATH: ${{secrets.TARGET_DIR}}
        INSTANCE_DNS: ${{secrets.INSTANCE_DNS}}
        REMOTE_PATH: ${{secrets.TARGET_DIR}}
        USERNAME: ${{ secrets.REMOTE_USER }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        $remotePath = $env:REMOTE_PATH
        $localPath = $env:LOCAL_PATH
        $instancePublicDns = $env:INSTANCE_DNS
        $username = $env:USERNAME
        $password = $env:PASSWORD

        # Mapeia a unidade de rede temporária usando SMB
        New-PSDrive -Name Z -PSProvider FileSystem -Root "\\$instancePublicDns\$remotePath" -Credential (New-Object System.Management.Automation.PSCredential -ArgumentList @($username, (ConvertTo-SecureString -AsPlainText $password -Force)))

        # Copia os arquivos para a unidade de rede mapeada
        Copy-Item -Path $localPath\* -Destination Z\

        # Desconecta a unidade de rede mapeada
        Remove-PSDrive -Name Z

